#Read table
library(dplyr)
fulldata<-read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".", as.is = TRUE)
str(fulldata)
data<-filter(fulldata, Date=="1/2/2007" | Date=="2/2/2007")
dim(data)
head(data)
str(data)
data$Global_active_power<-as.numeric(data$Global_active_power)
dateandtime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)
str(data)

#Plot 3
png("plot3.png", width=480, height=480, units = "px")
plot(dateandtime, data$Sub_metering_1, type="n",xlab="",ylab="Energy sub metering")
lines(dateandtime, data$Sub_metering_1)
lines(dateandtime, data$Sub_metering_2, col="red")
lines(dateandtime, data$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.off()
