#Read table
library(dplyr)
fulldata<-read.table("household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".", as.is = TRUE)
str(fulldata)
data<-filter(fulldata, Date=="1/2/2007" | Date=="2/2/2007")
dim(data)
head(data)
str(data)
data$Global_active_power<-as.numeric(data$Global_active_power)
dateandtime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
data$Sub_metering_1<-as.numeric(data$Sub_metering_1)
data$Sub_metering_2<-as.numeric(data$Sub_metering_2)
data$Sub_metering_3<-as.numeric(data$Sub_metering_3)
data$Voltage<-as.numeric(data$Voltage)
str(data)

#Plot 4
png("plot4.png", width=480, height=480, units = "px")
par(mfrow = c(2, 2)) 
plot(dateandtime, data$Global_active_power, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(dateandtime, data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dateandtime, data$Sub_metering_1, type="l", ylab="Energy Submetering", xlab="")
lines(dateandtime, data$Sub_metering_2, type="l", col="red")
lines(dateandtime, data$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(dateandtime, data$Global_active_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
